headmanpages/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index_headman'),
    path('logout/', views.logout_view, name='logout_headman'),
    path('options/', views.options, name='options_headman'),
    path('save_attendance/', views.save_attendance, name='save_attendance'),
    path('add_student/', views.add_student, name='add_student'),
    path('del_student/', views.del_student, name='del_student'),
    path('update_account/', views.update_account, name='update_account_headman'),
]

webway/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('corepages.urls')),
    path('administrator/', include('adminpages.urls')),
    path('headman/', include('headmanpages.urls')),
    path('teacher/', include('teacherpages.urls')),
]

headmanpages/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AccessWeeksTable(models.Model):
    week = models.OneToOneField('WeeksTable', models.DO_NOTHING, db_column='week', primary_key=True)  # The composite primary key (week, subgroup) found, that is not supported. The first column is selected.
    subgroup = models.ForeignKey('SubgroupsTable', models.DO_NOTHING, db_column='subgroup')
    color_sent = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'access_weeks_table'
        unique_together = (('week', 'subgroup'),)


class AttendanceTable(models.Model):
    id_student = models.OneToOneField('StudentsTable', models.DO_NOTHING, db_column='id_student', primary_key=True)  # The composite primary key (id_student, id_week) found, that is not supported. The first column is selected.
    id_week = models.ForeignKey('WeeksTable', models.DO_NOTHING, db_column='id_week')
    attendance_respectfully = models.PositiveIntegerField(blank=True, null=True)
    attendance_disrespectfully = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'attendance_table'
        unique_together = (('id_student', 'id_week'),)


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()
    key_subgroups = models.ForeignKey('SubgroupsTable', models.DO_NOTHING, db_column='key_subgroups', blank=True, null=True)
    patronymic = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class CommentsTable(models.Model):
    id_student = models.OneToOneField('StudentsTable', models.DO_NOTHING, db_column='id_student', primary_key=True)
    id_week = models.ForeignKey('WeeksTable', models.DO_NOTHING, db_column='id_week')
    comment = models.CharField(max_length=200, blank=True, null=True)
    color = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'comments_table'
        unique_together = (('id_student', 'id_week'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class GroupsTable(models.Model):
    id_groups_table = models.AutoField(primary_key=True)
    groups_name = models.CharField(unique=True, max_length=45)

    class Meta:
        managed = False
        db_table = 'groups_table'


class StudentsTable(models.Model):
    id_students_table = models.AutoField(primary_key=True)
    student_name = models.CharField(max_length=45)
    key_subgroup = models.ForeignKey('SubgroupsTable', models.DO_NOTHING, db_column='key_subgroup')

    class Meta:
        managed = False
        db_table = 'students_table'


class SubgroupsTable(models.Model):
    id_subgroups_table = models.AutoField(primary_key=True)
    subgroup_name = models.CharField(unique=True, max_length=45)
    key_group = models.ForeignKey(GroupsTable, models.DO_NOTHING, db_column='key_group')

    class Meta:
        managed = False
        db_table = 'subgroups_table'


class WeeksTable(models.Model):
    id_weeks_table = models.AutoField(primary_key=True)
    week_name = models.CharField(unique=True, max_length=45)

    class Meta:
        managed = False
        db_table = 'weeks_table'

headmanpages/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth import logout
from .models import StudentsTable, AuthUser, AttendanceTable, SubgroupsTable, AccessWeeksTable, WeeksTable
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password, make_password
from webway.decorators import group_required
import json

@login_required
@group_required('headman')
def index(request):
    current_headman  = AuthUser.objects.get(username = request.user)
    subgroup_key = current_headman.key_subgroups
    patronymic = current_headman.patronymic if current_headman.patronymic else ''
    groupmates = StudentsTable.objects.filter(key_subgroup = subgroup_key).order_by('student_name')
    weeks_access = AccessWeeksTable.objects.filter(subgroup = subgroup_key.id_subgroups_table).values('week')
    weeks = []
    for item in weeks_access:
        week = item['week']
        weeks.append(WeeksTable.objects.get(id_weeks_table = week))
    #weeks = WeeksTable.objects.filter(id_weeks_table = weeks_access).order_by('week')
    return render(request, 'headmanpages/startpage.html', {'subgroup_key': subgroup_key, 'groupmates': groupmates, 'weeks': weeks, 'name': current_headman.first_name, 'patronymic': patronymic})

@login_required
@group_required('headman')
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required
@group_required('headman')
def save_attendance(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.POST['data'])  # Преобразуем строку JSON в список словарей
            week = data[0]['week_id']
            for item in data:
                id_student = item['student_id']
                respectfully = item['respectfully']
                disrespectfully = item['disrespectfully']
                if (respectfully == 0):
                    respectfully = None
                if (disrespectfully == 0):
                    disrespectfully = None
                if (respectfully == disrespectfully == None):
                    AttendanceTable.objects.filter(id_student_id=id_student, id_week_id=week).delete()
                else:
                    attendance = AttendanceTable.objects.filter(id_student=id_student, id_week=week).first()
                    if attendance:
                        AttendanceTable.objects.filter(id_student=id_student, id_week=week).update(attendance_respectfully=None,attendance_disrespectfully=(disrespectfully or 0) + (respectfully or 0))
                    else:
                        attendance = AttendanceTable.objects.create(
                            id_student_id=id_student,
                            id_week_id=week,
                            attendance_respectfully= None,
                            attendance_disrespectfully = (disrespectfully or 0) + (respectfully or 0)
                        )
            st = data[0]['student_id']
            student_for_subgroups_search = StudentsTable.objects.filter(id_students_table = st).first()
            existing_record = AccessWeeksTable.objects.filter(week=week, subgroup=student_for_subgroups_search.key_subgroup).update(color_sent = 'Y')

            return JsonResponse({'success': True})
        except Exception as e:
            return JsonResponse({'success': False, 'message': str(e)})
    else:
        return JsonResponse({'success': False, 'message': 'Метод запроса не поддерживается'})

@login_required
@group_required('headman')
def add_student(request):
    if request.method == 'POST':
        student_name = request.POST.get('student_name')
        key_subgroup_id = request.POST.get('key_subgroup')  # Получаем ID подгруппы
        key_subgroup = get_object_or_404(SubgroupsTable, id_subgroups_table=key_subgroup_id)  # Получаем объект SubgroupsTable по ID
        searchStudent = StudentsTable.objects.filter(student_name=student_name, key_subgroup=key_subgroup).first()
        try:
            if searchStudent:
                raise Exception("Студент с таким именем уже есть в данной группе!")
            new_student = StudentsTable.objects.create(student_name=student_name, key_subgroup=key_subgroup)
            success = True
            message = "Студент успешно добавлен!"
        except Exception as e:
            success = False
            message = str(e)
        
        return JsonResponse({'success': success, 'message': message})
    else:
        return JsonResponse({'success': False, 'message': 'Метод запроса не поддерживается'})
    
@login_required
@group_required('headman')
def del_student(request):
    if request.method == 'POST':
        student_name = request.POST.get('student_name')
        key_subgroup_id = request.POST.get('key_subgroup')  # Получаем ID подгруппы
        key_subgroup = get_object_or_404(SubgroupsTable, id_subgroups_table=key_subgroup_id)  # Получаем объект SubgroupsTable по ID
        try:
            student = StudentsTable.objects.get(student_name=student_name, key_subgroup=key_subgroup)
            student.delete()
            success = True
            message = "Студент успешно отчислен!"
        except Exception as e:
            success = False
            message = str(e)
        
        return JsonResponse({'success': success, 'message': message})
    else:
        return JsonResponse({'success': False, 'message': 'Метод запроса не поддерживается'})

@login_required
@group_required('headman')
def options(request):
    user = AuthUser.objects.get(username = request.user)
    return render(request, 'headmanpages/options.html', {'user': user})

@login_required
@group_required('headman')
def update_account(request):
    if request.method == 'POST':
        
        user = AuthUser.objects.get(username = request.user)
        current_password = request.POST.get('current_password')
        if not check_password(current_password, user.password):
            return render(request, 'headmanpages/options.html', {'message': 'Неверный текущий пароль'})
        
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        mail = request.POST.get('mail')
        patronymic = request.POST.get('patronymic')

        if first_name:
            user.first_name = first_name
        if last_name:
            user.last_name = last_name
        if patronymic:
            user.patronymic = patronymic
        if mail:
            user.email = mail
        if password:
            hashed_password = make_password(password)
            user.password = hashed_password
        
        user.save()
        return render(request, 'headmanpages/options.html', {'message': 'Данные аккаунта успешно обновлены!'})

    return render(request, 'headmanpages/options.html')

headmanpages/templates/headmanpages/options.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Настройки</title>
    <link rel="stylesheet" href="{% static 'headmanpages/css/options.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        .container.rounded {
            border: 2px solid #8B2222;
            background-color: #FBE4C5;
            border-radius: 10px;
            padding: 15px;
        }
        
        .container.rounded-main {
            border: 2px solid #8B2222;
            padding: 15px;
            background-color: #FBE4C5;
        }

        #searchResultsContainer {
            max-height: 30px;
            overflow-y: auto;
        }

        .btn-primary {
            background-color: #8B2222 !important;
            border-color: #8B2222 !important;
        }

        .btn-primary:not(:disabled):not(.disabled):active,
        .btn-primary:not(:disabled):not(.disabled).active,
        .show>.btn-primary.dropdown-toggle {
            color: #ffffff !important;
        }

        .btn-primary:hover {
            background-color: #A84242 !important;
            border-color: #A84242 !important;
        }
    </style>
</head>
<body>
    <div class="container rounded-main" style="max-width: 100%;">
        <div class="row">
            <div class="col-md-6 text-left">
                <div class="row">
                    <div class="col-md-2">
                        <a href="{% url 'index_headman' %}" class="btn btn-primary btn-lg" style="white-space: nowrap;">На главную</a>
                    </div>
                    <div class="col-md-2">
                        <a href="{% url 'options_headman' %}" class="btn btn-primary btn-lg">Настройки</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div style="text-align: center;">
        <img src="{% static 'headmanpages/icons/chelgu-logo.png' %}" alt="logo" style="max-width: 130px; max-height: 130px; margin-top: -4%;">
    </div>

    <div class="container mt-4" style="text-align: center; max-width: 100%;">
        <div class="container rounded" style="width: 500px !important;">
            {% if message %}
                <p style="font-size: 25px; font-weight: bold; color: #8B2222;">{{ message }}</p>
            {% endif %}
            <form method="post" action="{% url 'update_account_headman' %}" id="update_account_form" style="font-size: 25px; font-weight: bold;">
                {% csrf_token %}
                <div class="form-group">
                    <label for="current_password">Актуальный пароль:</label>
                    <input type="password" class="form-control" id="id_current_password" name="current_password">
                </div>
                <div class="form-group">
                    <label for="id_last_name">Фамилия:</label>
                    <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ user.last_name }}">
                </div>
                <div class="form-group">
                    <label for="id_first_name">Имя:</label>
                    <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ user.first_name }}">
                </div>
                <div class="form-group">
                    <label for="id_patronymic">Отчество:</label>
                    <input type="text" class="form-control" id="id_patronymic" name="patronymic" value="{{ user.patronymic|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="mail">Почта:</label>
                    <input type="email" class="form-control" id="id_mail" name="mail" value="{{ user.email }}">
                </div> 
                <div class="form-group">
                    <label for="id_password">Новый пароль:</label>
                    <input type="password" class="form-control" id="id_password" name="password">
                </div>
                <div class="form-group">
                    <label for="id_password">Повторите пароль:</label>
                    <input type="password" class="form-control" id="id_password_2" name="password_2">
                </div>
                <div id="password_error" style="color: red; display: none;">Пароли не совпадают</div>
                <button type="submit" class="btn btn-primary">Сохранить изменения</button>
            </form>
            
        </div>
    </div>

    <script>
        document.getElementById("update_account_form").addEventListener("submit", function(event) {
            var password1 = document.getElementById("id_password").value;
            var password2 = document.getElementById("id_password_2").value;
        
            if (password1 !== password2) {
                event.preventDefault();
                document.getElementById("password_error").style.display = "block";
            }
        });
    </script>
</body>
</html>